from haptic.gym.envs.toy_text.blackjack import BlackjackEnv
from haptic.gym.envs.toy_text.roulette import RouletteEnv
from haptic.gym.envs.toy_text.frozen_lake import FrozenLakeEnv
from haptic.gym.envs.toy_text.nchain import NChainEnv
from haptic.gym.envs.toy_text.hotter_colder import HotterColder
from haptic.gym.envs.toy_text.guessing_game import GuessingGame
from haptic.gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from haptic.gym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from haptic.gym.envs.toy_text.cliffwalking import CliffWalkingEnv
