# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.15
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.15"
        
      # - name: Set up SSH key
      #   run: |
      #       mkdir -p ~/.ssh
      #       echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #       chmod 600 ~/.ssh/id_rsa
      #       ssh-keyscan github.com >> ~/.ssh/known_hosts
            
      - name: Initialize and update submodules
        run: |
            git submodule update --init --recursive
  
      - name: Install submodules
        run: |
              cd gym  
              pip install .
              cd ..
              cd stable_baselines3
              pip install .
              cd ..
            
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint mypy pytest
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with Pylint
        run: |
          pylint src/haptic --disable=no-member |& tee pylint.log
      - name: Style checking with mypy
        run: |
          mypy src/haptic/ --ignore-missing-imports |& tee mypy.log
      - name: Test with pytest
        run: |
          pytest
