name: Linters

on: pull_request

# permissions: write-all

jobs:
  Testing:
    runs-on: ubuntu-latest
    name: Comment for linters
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
              
      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
  
      - name: Install submodules
        run: |
              cd gym  
              pip install .
              cd ..
              cd stable_baselines3
              pip install .
              cd ..

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint mypy pytest-cov coverage
          pip install -r requirements.txt
          pip install -e .

      - name: Test with pytest
        run: |
          pytest --cov=haptic
          echo "${PIPESTATUS[0]}" |& tee coverage_status.log
          python3 -m coverage report --ignore-errors --show-missing |& tee coverage.log

      - name: Pylint Style Checker
        run: |
          pylint src/haptic/ --disable=no-member |& tee pylint.txt
          echo "$PIPESTATUS" >> pylint_status.txt

      - name: Mypy Style Checker
        run: |
          mypy src/haptic/ --ignore-missing-imports |& tee mypy.txt
          echo "$PIPESTATUS" >> mypy_status.txt

      - name: Parsing linters
        run: python scripts/linters_parser.py

      # - name: Comment PR
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     filePath: linters.txt
